# Generated by Django 4.0.7 on 2022-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='sensor1',
            field=models.FloatField(blank=True, default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='sensor2',
            field=models.FloatField(blank=True, default=0.0, max_length=50),
        ),
    ]
