# Generated by Django 4.0.7 on 2022-10-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_content_message_sensor1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='allDevices',
            fields=[
                ('d_id', models.CharField(default=0, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='d_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.alldevices'),
            preserve_default=False,
        ),
    ]
