# Generated by Django 4.0.7 on 2022-10-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alldevices_remove_message_id_message_d_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
    ]
