# Generated by Django 4.0.7 on 2022-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_room_remove_message_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pin1Status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pin2Status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
